#ifndef CAR_WEB_SERVER_VERSION_H
#define CAR_WEB_SERVER_VERSION_H

#ifndef AV_STRINGIFY
#define AV_STRINGIFY(s) AV_TOSTRING(s)
#endif // AV_STRINGIFY

#ifndef AV_TOSTRING
#define AV_TOSTRING(s) #s
#endif // AV_TOSTRING

#ifndef AV_VERSION_DOT
#define AV_VERSION_DOT(a, b, c) a##.##b##.##c
#endif // AV_VERSION_DOT

#ifndef AV_VERSION
#define AV_VERSION(a, b, c) AV_VERSION_DOT(a, b, c)
#endif // AV_VERSION

#define CAR_WEB_SERVER_VER_MAJOR 1
#define CAR_WEB_SERVER_VER_MINOR 0
#define CAR_WEB_SERVER_VER_PATCH 0
#define CAR_WEB_SERVER_VERSION AV_STRINGIFY(AV_VERSION(CAR_WEB_SERVER_VER_MAJOR, CAR_WEB_SERVER_VER_MINOR, CAR_WEB_SERVER_VER_PATCH))

#endif // CAR_WEB_SERVER_VERSION_H