#ifndef PC_SERVER_VERSION_H
#define PC_SERVER_VERSION_H
#define PC_SERVER_VERSION "1.0.0"
#define PC_SERVER_VER_MAJOR 1
#define PC_SERVER_VER_MINOR 0
#define PC_SERVER_VER_PATCH 0
#endif // PC_SERVER_VERSION_H