#ifndef SRS_SERVER_VERSION_H
#define SRS_SERVER_VERSION_H
#define SRS_SERVER_VERSION "1.0.0"
#define SRS_SERVER_VER_MAJOR 1
#define SRS_SERVER_VER_MINOR 0
#define SRS_SERVER_VER_PATCH 0
#endif // SRS_SERVER_VERSION_H