#ifndef WEB_SERVER_VERSION_H
#define WEB_SERVER_VERSION_H
#define WEB_SERVER_VERSION "1.0.0"
#define WEB_SERVER_VER_MAJOR 1
#define WEB_SERVER_VER_MINOR 0
#define WEB_SERVER_VER_PATCH 0
#endif // WEB_SERVER_VERSION_H